/**
 * Canonical audit action names for LMS API (stdout JSON lines with `type: "audit"`).
 */
export const AUDIT_ACTIONS = {
  ENROLLMENT_CREATE: "enrollment.create",
  ENROLLMENT_LIST_READ: "enrollment.list_read",
  PROGRESS_WRITE: "progress.write",
  PROGRESS_LIST_READ: "progress.list_read",
  ASSESSMENT_DRAFT_SAVE: "assessment.draft_save",
  ASSESSMENT_SUBMIT: "assessment.submit",
  LEARNERS_DIRECTORY_READ: "learners.directory_read",
  LEARNERS_PROVISION: "learners.provision",
  CATEGORIES_DIRECTORY_READ: "categories.directory_read",
  CATEGORY_WRITE: "category.write",
  COURSE_CATEGORY_LINKS_WRITE: "course.category_links_write",
  COURSE_UPDATE: "course.update",
  REPORTS_PROGRESS_READ: "reports.progress_read",
  LESSON_PLAYBACK_READ: "lesson.playback_read",
  LESSON_PATCH: "lesson.patch",
  LESSON_READING_READ: "lesson.reading_read",
  LESSON_READING_PATCH: "lesson.reading_patch",
  LESSON_GLOSSARY_LIST_READ: "lesson.glossary_list_read",
  LESSON_GLOSSARY_CREATE: "lesson.glossary_create",
  LESSON_GLOSSARY_PATCH: "lesson.glossary_patch",
  LESSON_GLOSSARY_ARCHIVE: "lesson.glossary_archive",
  LESSON_EXTERNAL_LINK_LIST_READ: "lesson.external_link_list_read",
  LESSON_EXTERNAL_LINK_CREATE: "lesson.external_link_create",
  LESSON_EXTERNAL_LINK_PATCH: "lesson.external_link_patch",
  LESSON_EXTERNAL_LINK_ARCHIVE: "lesson.external_link_archive",
  LESSON_FILE_LIST_READ: "lesson.file_list_read",
  LESSON_FILE_UPLOAD_INIT: "lesson.file_upload_init",
  LESSON_FILE_DOWNLOAD: "lesson.file_download",
  LESSON_FILE_REORDER: "lesson.file_reorder",
  LESSON_FILE_PATCH: "lesson.file_patch",
  LESSON_FILE_ARCHIVE: "lesson.file_archive",
  SCORM_PACKAGE_UPLOAD_INIT: "lesson.scorm_package_upload_init",
  SCORM_PACKAGE_PROCESS: "lesson.scorm_package_process",
  SCORM_PACKAGE_READ: "lesson.scorm_package_read",
  SCORM_RUNTIME_READ: "lesson.scorm_runtime_read",
  SCORM_SESSION_READ: "lesson.scorm_session_read",
  SCORM_SESSION_PATCH: "lesson.scorm_session_patch"
} as const;
